### ISSUE TITLE
Removes CDATA tag

### ISSUE THREAD

**Issue by prabushi** [riversun/xml-beautify#6]
It removes the CDATA tag within the xml tags while beautifying the content.

**Input**
` <sql><![CDATA[select * from &#xd;( select *  from (select username, customer_id, order_id from Order_History where username=:username) a&#xd;   where rownum <= :to )&#xd;where rnum <= :from]]></sql>`

**Output**
`<sql>select * from &#xd;( select *  from (select username, customer_id, order_id from Order_History where username=:username) a&#xd;   where rownum <= :to )&#xd;where rnum <= :from</sql>`

**Comment by aegam** [comment]
Seconding the issue of CDATA being removed during beautification as of the latest stable version (1.1.2).

The result of removing the `<![CDATA[ ... ]]>` encapsulation is invalid XML. Ideally, beautifying the XML shouldn't compromise its validity.
